package group14.finalproject.mytodotask

// FIREBASE DATABASE
const val TASK_FIREBASE_DATABASE = "TASK_FIREBASE_DATABASE"
const val TAG_FIREBASE_DATABASE = "TAG_FIREBASE_DATABASE"
const val RELATIONSHIP_FIREBASE_DATABASE = "RELATIONSHIP_FIREBASE_DATABASE"

// Name database
const val DATABASE_TASK_SUFFIX_NAME = "-NOTE.dbTasks"
const val DATABASE_TAG_SUFFIX_NAME = "-TAG.dbTasks"
const val DATABASE_RELATIONSHIP_SUFFIX_NAME = "-RELATIONSHIP.dbTasks"

// CODE FOR RESULT ACTIVITY
const val CODE_ADD_NEW_TASK = 1015
const val CODE_EDIT_TASK = 1016

// KEY FOR CHANGE DATA ACTIVITY
const val NEW_TASK_KEY = "NEW_TASK_KEY"
const val EDIT_TASK_KEY = "EDIT_TASK_KEY"

// CODE FOR POSITION
const val CODE_EDIT_TASK_POSITION = "CODE_EDIT_TASK_POSITION"
const val CODE_DELETE_TASK_POSITION = "CODE_DELETE_TASK_POSITION "

// SHARED PREFERENCES
const val USERNAME_KEY = "USERNAME_KEY"
const val PREFERENCES_NAME = "KHTN_PREF"
const val USERNAME_DEFAULT = "GUEST"

// SEARCH ACTIVITY
const val FLAG_TITLE = 0
const val FLAG_TAGS = 1
const val FLAG_COMPLETED = 21
const val FLAG_UNCOMPLETED = 22
const val FLAG_NONE = 23